#!/usr/bin/env python3

import os, errno
from sys import argv, stdout, stderr
import re
import json
import atexit
import secrets
from copy import deepcopy
from datetime import datetime, timedelta
from subprocess import CalledProcessError, Popen, run, DEVNULL, PIPE
from shutil import which
from enum import Enum, IntEnum
from collections import namedtuple
from struct import unpack_from, calcsize
from select import poll
from time import sleep
from timeit import default_timer as timer
from ctypes import CDLL, get_errno, c_int
from ctypes.util import find_library
from errno import EINTR
from termios import FIONREAD
from fcntl import ioctl
from io import FileIO
from os import fsencode, fsdecode

CK_DIR = os.path.dirname(os.path.realpath(__file__))

toolchain = {
    'default': {
        'CROSS_COMPILE': 'toolchain/gcc-cfp/gcc-cfp-jopp-only/aarch64-linux-android-4.9/bin/aarch64-linux-android-',
        'CLANG_TRIPLE': 'toolchain/clang/host/linux-x86/clang-4639204-cfp-jopp/bin/aarch64-linux-gnu-',
        'CC': 'toolchain/clang/host/linux-x86/clang-4639204-cfp-jopp/bin/clang'
    },
    'cruel': {
        'CROSS_COMPILE': 'toolchain/bin/aarch64-cruel-elf-'
    },
    'samsung': {
        'CROSS_COMPILE': 'toolchain/gcc-cfp/gcc-cfp-jopp-only/aarch64-linux-android-4.9/bin/aarch64-linux-android-',
        'CLANG_TRIPLE': 'toolchain/clang/host/linux-x86/clang-r349610-jopp/bin/aarch64-linux-gnu-',
        'CC': 'toolchain/clang/host/linux-x86/clang-r349610-jopp/bin/clang'
    },
    'google': {
        'CROSS_COMPILE': 'toolchain/aarch64-linux-android-4.9/bin/aarch64-linux-android-',
        'CLANG_TRIPLE': 'toolchain/llvm/bin/aarch64-linux-android-',
        'CC': 'toolchain/llvm/bin/clang',
        'LD': 'toolchain/llvm/bin/ld.lld',
        'AR': 'toolchain/llvm/bin/llvm-ar',
        'NM': 'toolchain/llvm/bin/llvm-nm',
        'OBJCOPY': 'toolchain/llvm/bin/llvm-objcopy',
        'OBJDUMP': 'toolchain/llvm/bin/llvm-objdump',
        'READELF': 'toolchain/llvm/bin/llvm-readelf',
        'OBJSIZE': 'toolchain/llvm/bin/llvm-size',
        'STRIP': 'toolchain/llvm/bin/llvm-strip',
        'LDGOLD': 'toolchain/aarch64-linux-android-4.9/bin/aarch64-linux-android-ld.gold',
        'LLVM_AR': 'toolchain/llvm/bin/llvm-ar',
        'LLVM_DIS': 'toolchain/llvm/bin/llvm-dis'
    },
    'proton': {
        'CROSS_COMPILE': 'toolchain/bin/aarch64-linux-gnu-',
        'CROSS_COMPILE_ARM32': 'toolchain/bin/arm-linux-gnueabi-',
        'CC': 'toolchain/bin/clang',
        'LD': 'toolchain/bin/ld.lld',
        'AR': 'toolchain/bin/llvm-ar',
        'NM': 'toolchain/bin/llvm-nm',
        'OBJCOPY': 'toolchain/bin/llvm-objcopy',
        'OBJDUMP': 'toolchain/bin/llvm-objdump',
        'READELF': 'toolchain/bin/llvm-readelf',
        'OBJSIZE': 'toolchain/bin/llvm-size',
        'STRIP': 'toolchain/bin/llvm-strip',
        'LDGOLD': 'toolchain/bin/aarch64-linux-gnu-ld.gold',
        'LLVM_AR': 'toolchain/bin/llvm-ar',
        'LLVM_DIS': 'toolchain/bin/llvm-dis'
    },
    'arter97': {
        'CROSS_COMPILE': 'toolchain/bin/aarch64-elf-'
    },
    'arm': {
        'CROSS_COMPILE': 'toolchain/bin/aarch64-none-elf-'
    },
    'system-gcc': {
        'CROSS_COMPILE': 'aarch64-linux-gnu-'
    },
    'system-clang': {
        'CC': 'clang',
        'CROSS_COMPILE': 'aarch64-linux-gnu-',
        'CROSS_COMPILE_ARM32': 'arm-linux-gnu-'
    }
}

models = {
    'G970F': {
        'config': 'exynos9820-beyond0lte_defconfig'
    },
    'G973F': {
        'config': 'exynos9820-beyond1lte_defconfig'
    },
    'G975F': {
        'config': 'exynos9820-beyond2lte_defconfig'
    },
    'G977B': {
        'config': 'exynos9820-beyondx_defconfig'
    },
    'G977N': {
        'config': 'exynos9820-beyondxks_defconfig'
    },
    'N975F': {
        'config': 'exynos9820-d2s_defconfig'
    },
    'N976B': {
        'config': 'exynos9820-d2x_defconfig'
    },
    'N976N': {
        'config': 'exynos9820-d2xks_defconfig'
    }
}

OBJTREE_SIZE_GB = 3


_libc = None
def _libc_call(function, *args):
    """Wrapper which raises errors and retries on EINTR."""
    while True:
        rc = function(*args)
        if rc != -1:
            return rc
        errno = get_errno()
        if errno != EINTR:
            raise OSError(errno, os.strerror(errno))

Event = namedtuple('Event', ['wd', 'mask', 'cookie', 'name'])

_EVENT_FMT = 'iIII'
_EVENT_SIZE = calcsize(_EVENT_FMT)

class INotify(FileIO):
    fd = property(FileIO.fileno)
    inotify_raw_events = []
    topdir = 1
    paths = {}
    event_files = set()

    def __init__(self, inheritable=False, nonblocking=False):
        try:
            libc_so = find_library('c')
        except RuntimeError:
            libc_so = None
        global _libc; _libc = _libc or CDLL(libc_so or 'libc.so.6', use_errno=True)
        O_CLOEXEC = getattr(os, 'O_CLOEXEC', 0) # Only defined in Python 3.3+
        flags = (not inheritable) * O_CLOEXEC | bool(nonblocking) * os.O_NONBLOCK
        FileIO.__init__(self, _libc_call(_libc.inotify_init1, flags), mode='rb')
        self._poller = poll()
        self._poller.register(self.fileno())

    def add_watch(self, path, mask):
        path = str(path) if hasattr(path, 'parts') else path
        wd = _libc_call(_libc.inotify_add_watch, self.fileno(), fsencode(path), mask)
        self.paths[wd] = path
        if path == '.':
            self.topdir = wd
        return wd

    def readraw(self, timeout=None, read_delay=None):
        data = self._readall()
        if not data and timeout != 0 and self._poller.poll(timeout):
            if read_delay is not None:
                sleep(read_delay / 1000.0)
            data = self._readall()
        return data

    def _readall(self):
        bytes_avail = c_int()
        ioctl(self, FIONREAD, bytes_avail)
        if not bytes_avail.value:
            return b''
        return os.read(self.fileno(), bytes_avail.value)

    def collect_events(self, timeout=1, read_delay=None):
        self.inotify_raw_events.append(self.readraw(timeout=timeout, read_delay=read_delay))

    @staticmethod
    def parse_events(data):
        pos = 0
        events = []
        while pos < len(data):
            wd, mask, cookie, namesize = unpack_from(_EVENT_FMT, data, pos)
            pos += _EVENT_SIZE + namesize
            name = data[pos - namesize : pos].split(b'\x00', 1)[0]
            events.append(Event(wd, mask, cookie, fsdecode(name)))
        return events

    def _gather_event_files(self):
        event_files = set()
        for data in self.inotify_raw_events:
            for event in self.parse_events(data):
                if event.wd != -1:
                    if event.wd == self.topdir:
                        event_files.add(event.name)
                    else:
                        event_files.add(os.path.join(self.paths[event.wd], event.name))
                else:
                    fatal("Missing events with SRC_REDUCE=y, try to use j=1")
        inotify_raw_events = []
        self.event_files.update(event_files)

    def get_event_files(self):
        self.collect_events()
        self._gather_event_files()
        return self.event_files

    def run(self, args):
        with Popen(args, stdout=stdout, stderr=stderr) as proc:
            while proc.poll() is None:
                self.collect_events()
            if proc.returncode:
                exit(proc.returncode)
        self._gather_event_files()

class flags(IntEnum):
    OPEN = 0x00000020  #: File was opened
    Q_OVERFLOW = 0x00004000  #: Event queue overflowed
    ONLYDIR = 0x01000000  #: only watch the path if it is a directory
    EXCL_UNLINK = 0x04000000  #: exclude events on unlinked objects

inotify = INotify()
watch_flags = flags.OPEN | flags.EXCL_UNLINK | flags.ONLYDIR
unused_files = set()


def get_toolchain_cc(compiler):
    cc = ''
    if 'CC' in toolchain[compiler]:
        cc = toolchain[compiler]['CC']
    else:
        cc = toolchain[compiler]['CROSS_COMPILE'] + 'gcc'
    return cc

def mount_tmpfs(target, req_mem_gb):
    if not os.path.ismount(target):
        meminfo = dict((i.split()[0].rstrip(':'),int(i.split()[1])) for i in open('/proc/meminfo').readlines())
        av_mem_gb = int(meminfo['MemAvailable'] / 1024 ** 2)
        if av_mem_gb >= req_mem_gb + 2:
            ret = run(['sudo', '--non-interactive',
                       'mount', '-t', 'tmpfs', '-o', 'rw,noatime,size=' + str(req_mem_gb) + 'G', 'tmpfs', target])
            if ret.returncode != 0:
                print('BUILD: error mounting tmpfs on ' + target, file=stderr)
            else:
                print('BUILD: tmpfs is mounted on ' + target)
        else:
            print('BUILD: will not mount tmpfs on ' + target + ' size ' + str(av_mem_gb) + 'G < ' + str(req_mem_gb + 2) + 'G')
    else:
        print(target + ' is already used as mountpoint', file=stderr)

def umount_tmpfs(target):
    if os.path.ismount(target):
        ret = run(['sudo', '--non-interactive', 'umount', target])
        if ret.returncode != 0:
            print("BUILD: error unmounting " + target, file=stderr)
        else:
            print("BUILD: " + target + " unmounted")

def inotify_install_watchers(inotify, dirname, watch_flags, exclude_dirs, exclude_files):
    inotify.add_watch(dirname, watch_flags)

    topdirs, unused_files = scandir(dirname)
    for d in exclude_dirs:
        topdirs.remove(d)
    for f in exclude_files:
        unused_files.remove(f)

    for dir in topdirs:
        for root, dirs, files in os.walk(dir, topdown=False):
            unused_files.update({ os.path.join(root, f) for f in files })
            for d in dirs:
                inotify.add_watch(os.path.join(root, d), watch_flags)

    return unused_files

def remove_files(*files):
    for f in files:
        try:
            os.remove(f)
        except FileNotFoundError:
            pass

def del_dirs(src_dir):
    for dirpath, _, _ in os.walk(src_dir, topdown=False):
        try:
            os.rmdir(dirpath)
        except OSError:
            pass

def mkdir(dirname):
    try:
        os.mkdir(dirname)
    except FileExistsError:
        pass

def scandir(dirname):
    topdirs = set()
    topfiles = set()
    with os.scandir(dirname) as it:
        for entry in it:
            if entry.is_dir():
                topdirs.add(entry.name)
            else:
                topfiles.add(entry.name)
    return topdirs, topfiles

def tool_exists(name):
    return which(name) is not None

def get_cores_num():
    return len(os.sched_getaffinity(0))

def check_env(var):
    isset = False
    v = os.environ.get(var, 'n')
    if v == 'y' or v == 'Y' or v == 'yes' or v == '1':
        isset = True
    return isset

def set_env(force=False, **env):
    for key, value in env.items():
        if force or key not in os.environ:
            os.environ[key] = value
        value = os.environ[key]
        print(key + '="' + value + '"')

def fatal(*args, **kwargs):
    print(*args, file=stderr, **kwargs)
    exit(1)

def print_usage():
    msg = f"""
Usage: {argv[0]} <stage> model=<model> name=<name> [+-]<conf1> [+-]<conf2> ...

<stage>: build stage. Required argument. mkimg by default.
Where <stage> can be one of: config, build, mkimg, pack
(:build, :mkimg, :pack). Each next stage will run all
previous stages first. Prefix ':' means skip all previous
stages.

model=<model> phone model name. Required argument.
The script will try to autodetect connected phone if
model is not specified. Supported models:
{list(models.keys())}
Use model=all to build all available kernels.

name=<name>: optional custom kernel name
Use this switch if you want to change the name in
your kernel.

toolchain=<compiler>: optional toolchain switch
Supported compilers: {list(toolchain.keys())}

os_patch_level=<date>: use patch date (YYYY-MM)
instead of default one from build.mkbootimg.<model>
file. For example: os_patch_level="2020-02"

O=dir will perform out of tree kernel build in dir.
The script will try to mount tmpfs in dir if there
is enough available memory.

[+-]<conf>: optional list of configuration switches.
Use prefix '+' to enable the configuration.
Use prefix '-' to disable the configuration.
You can check full list of switches and default ones in
kernel/configs/cruel*.conf directory.
One can use NODEFAULTS=y {argv[0]} +samsung ... to disable
all enabled by default configs.

If you want to flash the kernel, use: FLASH=y {argv[0]}
"""
    print(msg)

def parse_stage():
    stages = []
    modes = ['config', 'build', 'mkimg', 'pack']
    omodes = [':config', ':build', ':mkimg', ':pack']
    all_modes = modes + omodes

    if len(argv) > 1:
        mode = argv[1]
        if mode not in all_modes:
            if mode[0] == '+' or mode[0] == '-' or '=' in mode:
                mode = 'mkimg'
            else:
                print_usage()
                fatal('Please, specify the mode from {}.'.format(all_modes))
        else:
            argv.pop(1)
    else:
        mode = 'mkimg'

    if mode in omodes:
        if mode == ':config':
            stages = [] # special model for :config
                        # don't run make defconfig
                        # just generate config.json file
        else:
            stages = [mode[1:]]
    else:
        stages = modes[0:modes.index(mode)+1]

    return stages

def find_configs():
    configs = { 'kernel': {}, 'order': [] }
    prefix_len = len('cruel')
    suffix_len = len('.conf')
    nodefaults = check_env('NODEFAULTS')
    files = [f for f in os.listdir('kernel/configs/') if re.match('^cruel[+-]?.*\.conf$', f)]
    for f in files:
        if f == 'cruel.conf':
            continue
        name = f[prefix_len+1:]
        name = name[:-suffix_len]
        enabled = True if f[prefix_len:prefix_len+1] == '+' else False

        configs['kernel'][name] = {
            'path': os.path.join('kernel/configs', f),
            'enabled': enabled if not nodefaults else False,
            'default': enabled
        }
        if enabled and not nodefaults:
            configs['order'].append(name)
        configs['order'] = sorted(configs['order'])
    return configs

def save_config(file, configs):
    conf = deepcopy(configs)
    with open(file, 'w') as fh:
        json.dump(conf, fh, sort_keys=True, indent=4)

def load_config(file):
    with open(file, 'r') as fh:
        return json.load(fh)

def switch_config(opt, enable, configs):
    if opt in configs['kernel']:
        configs['kernel'][opt]['enabled'] = enable
    else:
        fatal("Unknown config '{}'.".format(opt))

    if enable:
        if opt in configs['order']:
            configs['order'].remove(opt)
        configs['order'].append(opt)
    else:
        if opt in configs['order']:
            configs['order'].remove(opt)

def parse_args():
    configs = find_configs()

    for arg in argv[1:]:
        if arg.find('=') != -1:
            (key, value) = arg.split('=', 1)

            enable = None
            if key[0] == '-' or key[0] == '+':
                enable = True if key[0] == '+' else False
                key = key[1:]

            if key not in [ 'name',
                            'model',
                            'os_patch_level',
                            'toolchain',
                            'magisk',
                            'O' ]:
                fatal('Unknown config {}.'.format(key))

            if enable == None:
                if key == 'model':
                    if value == 'all':
                        value = list(models.keys())
                    else:
                        value = value.split(',')
                configs[key] = value
            else:
                switch_config(key, enable, configs)

            if not value:
                fatal('Please, use {}="<name>".'.format(key))
            elif key == 'model':
                for m in value:
                    if m not in models:
                        fatal('Unknown device model: ' + m)
            elif key == 'os_patch_level':
                if not re.match(r'^\d{4}-\d{2}$', value):
                    fatal('Invalid OS patch level format. Use YYYY-MM.')
            elif key == 'toolchain':
                if value not in toolchain:
                    fatal('Unknown toolchain: ' + value)
            elif key == 'magisk':
                if value not in ['y', 'n']:
                    fatal('Invalid magisk value. Use y or n.')

        else:
            switch_config(arg, True, configs)

    if 'model' not in configs:
        configs['model'] = get_device_model()

    if 'name' not in configs:
        configs['name'] = configs['model']

    return configs

def get_device_model():
    try:
        return run(['adb', 'shell', 'getprop', 'ro.product.model'], check=True, capture_output=True, text=True).stdout.strip()
    except CalledProcessError:
        fatal('Could not detect device model. Please specify it using model=<model>.')

def run_make_cmd(configs, target, *args):
    env = os.environ.copy()
    env['ARCH'] = 'arm64'
    env['SUBARCH'] = 'arm64'
    env['KBUILD_BUILD_USER'] = 'Magisk'
    env['KBUILD_BUILD_HOST'] = 'Here'
    env['KBUILD_BUILD_TIMESTAMP'] = ''

    if 'toolchain' in configs:
        for k, v in toolchain[configs['toolchain']].items():
            env[k] = v

    if 'os_patch_level' in configs:
        env['KBUILD_BUILD_TIMESTAMP'] = configs['os_patch_level']

    if 'O' in configs:
        env['KBUILD_OUTPUT'] = configs['O']

    if 'PLATFORM_VERSION' in env:
        print('PLATFORM_VERSION="' + env['PLATFORM_VERSION'] + '"')
    if 'ANDROID_MAJOR_VERSION' in env:
        print('ANDROID_MAJOR_VERSION="' + env['ANDROID_MAJOR_VERSION'] + '"')
    print('KBUILD_BUILD_TIMESTAMP="' + env['KBUILD_BUILD_TIMESTAMP'] + '"')

    cmd = ['make', '-j' + str(get_cores_num()), target] + list(args)

    print('Toolchain: ' + (configs['toolchain'] if 'toolchain' in configs else 'default'))
    print('Build date: ' + (env['KBUILD_BUILD_TIMESTAMP'] if env['KBUILD_BUILD_TIMESTAMP'] else datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')))
    print('Name: ' + configs['name'])
    print('Model: ' + configs['model'])
    print('Configuration:')
    for k, v in configs['kernel'].items():
        print('\t' + k + ' (default: ' + ('On' if v['default'] else 'Off') + ')')

    if 'os_patch_level' in configs:
        print('OS Patch Level: ' + configs['os_patch_level'])

    print('ARCH="' + env['ARCH'] + '"')
    if 'PLATFORM_VERSION' in env:
        print('PLATFORM_VERSION="' + env['PLATFORM_VERSION'] + '"')
    if 'ANDROID_MAJOR_VERSION' in env:
        print('ANDROID_MAJOR_VERSION="' + env['ANDROID_MAJOR_VERSION'] + '"')
    print('KBUILD_BUILD_TIMESTAMP="' + env['KBUILD_BUILD_TIMESTAMP'] + '"')

    run(cmd, env=env, check=True)

def disable_magisk_initramfs_source(output_dir):
    config_path = os.path.join(output_dir, '.config')
    if not os.path.exists(config_path):
        print(f"Warning: .config file not found at {config_path}. Skipping Magisk initramfs source disabling.", file=stderr)
        return

    lines = []
    modified = False
    with open(config_path, 'r') as f:
        for line in f:
            if line.startswith('CONFIG_INITRAMFS_SOURCE=') and 'usr/magisk' in line:
                print(f"Disabling CONFIG_INITRAMFS_SOURCE for Magisk: {line.strip()}")
                lines.append('# ' + line) # Comment out the line
                lines.append('CONFIG_INITRAMFS_SOURCE=""\n') # Set it to empty
                modified = True
            else:
                lines.append(line)

    if modified:
        with open(config_path, 'w') as f:
            f.writelines(lines)
        print("Successfully disabled Magisk initramfs source in .config.")
    else:
        print("No Magisk initramfs source found in .config to disable.")

def build_kernel(configs):
    output_dir = configs['O'] if 'O' in configs else '.'

    if 'O' in configs:
        mkdir(configs['O'])
        mount_tmpfs(configs['O'], OBJTREE_SIZE_GB)

    try:
        # Clean the kernel build directory
        run_make_cmd(configs, 'mrproper')

        # Apply defconfig
        model_config = models[configs['model']]['config']
        run_make_cmd(configs, 'defconfig', model_config)

        # Disable CONFIG_INITRAMFS_SOURCE if it points to usr/magisk
        if 'magisk' in configs['kernel'] and configs['kernel']['magisk']['enabled']:
            disable_magisk_initramfs_source(output_dir)

        # Build the kernel
        run_make_cmd(configs, 'Image.gz')

        # Build modules
        run_make_cmd(configs, 'modules')

        # Install modules
        run_make_cmd(configs, 'modules_install')

    finally:
        if 'O' in configs:
            umount_tmpfs(configs['O'])

def mkimg(configs):
    pass

def pack(configs):
    pass

def main():
    stages = parse_stage()
    configs = parse_args()

    if 'config' in stages:
        save_config('config.json', configs)

    if 'build' in stages:
        build_kernel(configs)

    if 'mkimg' in stages:
        mkimg(configs)

    if 'pack' in stages:
        pack(configs)

    if 'magisk' in configs['kernel'] and configs['kernel']['magisk']['enabled']:
        update_magisk(configs['kernel']['magisk'].get('version'))
        print('Magisk Version: ' + configs['kernel']['magisk'].get('version', 'N/A'))

if __name__ == '__main__':
    main()


